"""
paper_tables_behavioral.py
==========================
Produce three paper-ready tables from the behavioral CSVs generated by
quant_behavioral.py.

Table A — Per-seed performance by condition
  Rows:    model × seed  (averaged across global and local)
  Columns: PB | B | ND | NS | F  (mean_contribution)
  Best condition per row is marked with *

Table B — Best condition per model (aggregated across seeds and settings)
  Rows:    model
  Columns: PB | B | ND | NS | F  (mean ± CI)
  Best condition per model is marked with *

Table C — Global vs Local differences per condition
  Rows:    model × condition
  Columns: mean_contribution | final_contribution | mean_payoff | exclusion_rate
  Values:  Δ (local − global) [95% CI]  — significant differences marked *

Outputs (saved to TABLE_DIR):
  table_A_per_seed.csv / .tex
  table_B_per_model.csv / .tex
  table_C_global_local.csv / .tex
"""

import os
import numpy as np
import pandas as pd
from tabulate import tabulate

# ─── Config ───────────────────────────────────────────────────────────────────

TABLE_DIR = "/data3/rasimura/social-norm-evo/figures/2026-03-20/behavioral_tables"

COND_ABBREV = {
    "PURE_BASELINE": "PB",
    "BASELINE":      "B",
    "NO_DISCUSSION": "ND",
    "NO_SELECTION":  "NS",
    "FULL":          "F",
}
COND_ORDER = ["PURE_BASELINE", "BASELINE", "NO_DISCUSSION", "NO_SELECTION", "FULL"]

MODELS = ["gpt", "llama", "mistral", "qwen"]

METRICS = ["mean_contribution", "final_contribution", "mean_payoff", "exclusion_rate"]
METRIC_LABELS = {
    "mean_contribution":  "Mean contrib.",
    "final_contribution": "Final contrib.",
    "mean_payoff":        "Mean payoff",
    "exclusion_rate":     "Excl. rate",
}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def load_tables():
    df  = pd.read_csv(os.path.join(TABLE_DIR, "run_metrics.csv"))
    gl  = pd.read_csv(os.path.join(TABLE_DIR, "global_local_comparisons.csv"))
    summ = pd.read_csv(os.path.join(TABLE_DIR, "summary_table.csv"))
    return df, gl, summ


def fmt_val(v, decimals=3):
    if pd.isna(v):
        return "—"
    return f"{v:.{decimals}f}"


def fmt_ci(mean, lo, hi, decimals=3, sig=False):
    """Format mean [lo, hi] with optional significance star."""
    star = "*" if sig else " "
    return f"{star}{mean:.{decimals}f} [{lo:.{decimals}f}, {hi:.{decimals}f}]"


def save_table(df_out, name, caption=""):
    csv_path = os.path.join(TABLE_DIR, f"{name}.csv")
    tex_path = os.path.join(TABLE_DIR, f"{name}.tex")
    df_out.to_csv(csv_path, index=False)
    print(f"  Saved CSV  → {csv_path}")

    # LaTeX
    latex = df_out.to_latex(
        index=False,
        escape=True,
        caption=caption,
        label=f"tab:{name}",
        column_format="l" + "r" * (len(df_out.columns) - 1),
    )
    with open(tex_path, "w") as f:
        f.write(latex)
    print(f"  Saved LaTeX → {tex_path}")


# ─── Table A — Per-seed, per-model performance by condition ───────────────────
#
# Focus metric: mean_contribution (averaged across global and local settings)
# Rows: (model, seed)  Columns: PB | B | ND | NS | F | Best

def build_table_A(df: pd.DataFrame) -> pd.DataFrame:
    # Average across global and local
    agg = (
        df.groupby(["model", "seed", "condition"])["mean_contribution"]
        .mean()
        .reset_index()
    )

    rows = []
    for model in MODELS:
        msub = agg[agg["model"] == model]
        for seed in sorted(msub["seed"].unique()):
            ssub = msub[msub["seed"] == seed].set_index("condition")
            row = {"Model": model.upper(), "Seed": seed}
            vals = {}
            for cond in COND_ORDER:
                abbr = COND_ABBREV[cond]
                v = ssub.loc[cond, "mean_contribution"] if cond in ssub.index else np.nan
                vals[cond] = v
                row[abbr] = fmt_val(v, 2)
            # mark best
            best_cond = max(vals, key=lambda c: vals[c] if not pd.isna(vals[c]) else -np.inf)
            best_abbr = COND_ABBREV[best_cond]
            row[best_abbr] = row[best_abbr] + "*"
            row["Best"] = best_abbr
            rows.append(row)

    return pd.DataFrame(rows, columns=["Model", "Seed"] +
                        [COND_ABBREV[c] for c in COND_ORDER] + ["Best"])


# ─── Table B — Best condition per model (mean ± CI across seeds & settings) ──
#
# Rows: model   Columns: PB | B | ND | NS | F
# Each cell: mean [CI_low, CI_high]  — best per row marked *

def build_table_B(summ: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for model in MODELS:
        msub = summ[(summ["model"] == model) & (summ["metric"] == "mean_contribution")]
        # average over global and local
        agg = msub.groupby("condition")[["mean", "ci_low", "ci_high"]].mean()

        row = {"Model": model.upper()}
        best_mean = -np.inf
        best_abbr = ""

        for cond in COND_ORDER:
            abbr = COND_ABBREV[cond]
            if cond not in agg.index:
                row[abbr] = "—"
                continue
            m  = agg.loc[cond, "mean"]
            lo = agg.loc[cond, "ci_low"]
            hi = agg.loc[cond, "ci_high"]
            row[abbr] = fmt_val(m, 2) + f" [{lo:.2f}, {hi:.2f}]"
            if m > best_mean:
                best_mean = m
                best_abbr = abbr

        # mark best
        if best_abbr:
            row[best_abbr] = row[best_abbr] + "*"
        rows.append(row)

    return pd.DataFrame(rows, columns=["Model"] + [COND_ABBREV[c] for c in COND_ORDER])


# ─── Table C — Global vs Local differences ────────────────────────────────────
#
# Rows: model × condition
# Columns: one per metric → Δ [CI_low, CI_high]  (* if CI excludes 0)

def build_table_C(gl: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for model in MODELS:
        msub = gl[gl["model"] == model]
        for cond in COND_ORDER:
            csub = msub[msub["condition"] == cond].set_index("metric")
            row = {
                "Model":     model.upper(),
                "Condition": COND_ABBREV[cond],
            }
            for metric in METRICS:
                label = METRIC_LABELS[metric]
                if metric not in csub.index:
                    row[label] = "—"
                    continue
                md = csub.loc[metric, "mean_diff"]
                lo = csub.loc[metric, "ci_low"]
                hi = csub.loc[metric, "ci_high"]
                sig = (lo > 0) or (hi < 0)
                row[label] = fmt_ci(md, lo, hi, decimals=3, sig=sig)
            rows.append(row)

    return pd.DataFrame(rows, columns=["Model", "Condition"] +
                        [METRIC_LABELS[m] for m in METRICS])


# ─── Print helpers ────────────────────────────────────────────────────────────

def print_table(df, title):
    print(f"\n{'─'*70}")
    print(f"  {title}")
    print(f"{'─'*70}")
    print(tabulate(df, headers="keys", tablefmt="simple", showindex=False))


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    df, gl, summ = load_tables()

    print("\n" + "="*70)
    print("  PAPER-READY TABLES")
    print("="*70)
    print("  Conditions: PB=PURE_BASELINE  B=BASELINE  ND=NO_DISCUSSION")
    print("              NS=NO_SELECTION   F=FULL")
    print("  * = best condition per row (Tables A & B)")
    print("  * = CI excludes 0 (Table C, significant global vs local diff)")

    # ── Table A ──────────────────────────────────────────────────────────────
    tA = build_table_A(df)
    print_table(tA, "Table A — Mean contribution per seed (avg. global & local) | * = best")
    save_table(tA, "table_A_per_seed",
               caption="Mean contribution per condition, per seed (averaged across global and local settings). "
                       "Asterisk marks the best-performing condition for each run.")

    # ── Table B ──────────────────────────────────────────────────────────────
    tB = build_table_B(summ)
    print_table(tB, "Table B — Mean contribution per model (mean [95% CI] across seeds & settings) | * = best")
    save_table(tB, "table_B_per_model",
               caption="Mean contribution per condition and model, averaged across seeds and settings "
                       "(95\\% bootstrap CI). Asterisk marks the best-performing condition per model.")

    # ── Table C ──────────────────────────────────────────────────────────────
    tC = build_table_C(gl)
    print_table(tC, "Table C — Local − Global differences (Δ [95% CI]) | * = CI excludes 0")
    save_table(tC, "table_C_global_local",
               caption="Paired bootstrap differences (local $-$ global) per model and condition. "
                       "Values: $\\Delta$ [95\\% CI]. Asterisk marks comparisons where the CI excludes zero.")

    print("\nDone.")


if __name__ == "__main__":
    main()
